CREATE TABLE MARCA (
    ID_MARCA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100)
);

INSERT INTO MARCA VALUES (1, 'Samsung');
INSERT INTO MARCA VALUES (2, 'HP');
INSERT INTO MARCA VALUES (3, 'Lenovo');

COMMIT;


CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PRECIO NUMBER(10,2),
    ID_MARCA NUMBER,

    FOREIGN KEY (ID_MARCA)
        REFERENCES MARCA(ID_MARCA)
);

INSERT INTO PRODUCTO VALUES (1, 'Laptop HP', 4500, 2);
INSERT INTO PRODUCTO VALUES (2, 'Monitor Samsung', 1200, 1);

COMMIT;

CREATE TABLE DETALLE (
    ID_DETALLE NUMBER PRIMARY KEY,
    ID_FACTURA NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    PRECIO NUMBER(10,2),

    FOREIGN KEY (ID_FACTURA)
        REFERENCES FACTURA(ID_FACTURA),

    FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
);

INSERT INTO DETALLE VALUES (1, 1, 1, 2, 4500);
INSERT INTO DETALLE VALUES (2, 1, 2, 1, 1200);
INSERT INTO DETALLE VALUES (3, 2, 3, 1, 5000);

COMMIT;
INSERT INTO FACTURA VALUES (1, TO_DATE('2024-05-10','YYYY-MM-DD'), 2024, 1);

INSERT INTO FACTURA VALUES (2, TO_DATE('2025-03-15','YYYY-MM-DD'), 2025, 2);

INSERT INTO FACTURA VALUES (3, TO_DATE('2026-01-20','YYYY-MM-DD'), 2026, 3);

COMMIT;
CREATE SEQUENCE DET_SEQ START WITH 1 INCREMENT BY 1;


SELECT * FROM FACTURA;


INSERT INTO DETALLE VALUES (1, 1, 1, 2, 4500);
INSERT INTO DETALLE VALUES (2, 1, 2, 1, 1200);
INSERT INTO DETALLE VALUES (3, 2, 3, 1, 5000);

COMMIT;

SELECT * FROM PRODUCTO;